name: Compile Command
on:
  repository_dispatch:
    types: [compile-command]

env:
  arg1: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
  arg2: ${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
  ref: ${{ github.event.client_payload.pull_request.head.ref }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          ref: ${{ env.ref }}
          fetch-depth: 0

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v1
        id: package-engines-versions

      - name: Set up node ${{ steps.package-engines-versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.package-engines-versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.package-engines-versions.outputs.npmVersion }}"

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present

      - name: Setup git
        run: |
          git config --local user.email "npmbuildbot-nextcloud[bot]@users.noreply.github.com"
          git config --local user.name "npmbuildbot-nextcloud[bot]"  

      - name: Commit and push default
        # If the first argument starts with a /
        if: ${{ startsWith(env.arg1, '/') }}
        run: |
          git add ${{ github.workspace }}${{ env.arg1 }}
          git commit --signoff -m 'Compile assets'
          git push origin ${{ env.ref }}

      - name: Commit and push fixup
        if: ${{ env.arg1 == 'fixup' }}
        run: |
          git add ${{ github.workspace }}${{ env.arg2 }}
          git commit --fixup=HEAD --signoff
          git push origin ${{ env.ref }}

      - name: Commit and push amend
        if: ${{ env.arg1 == 'amend' }}
        run: |
          git add ${{ github.workspace }}${{ env.arg2 }}
          git commit --amend --no-edit --signoff
          git push --force origin ${{ env.ref }}
